### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.data.cp_dataset'

### ISSUE THREAD

**Issue by ThanhPham1987** [hywang2002/MV-VTON#10]
Hi
Where can I fiind this module?
from ldm.data.cp_dataset import CPDataset
Best regards,
Peter

**Comment by hywang2002** [comment]
![image](https://github.com/user-attachments/assets/4465b799-3f49-4fcf-80f1-55fa86e46cdc)
Thank you for your interest! You need to rename these file, as written in the readme.
