### ISSUE TITLE
where to download this model: "/mnt/pfs-mc0p4k/cvg/team/didonglin/why/my_huggingface/Paint-by-Example"

### ISSUE THREAD

**Issue by yatoubusha** [hywang2002/MV-VTON#12]
where to download this model: "/mnt/pfs-mc0p4k/cvg/team/didonglin/why/my_huggingface/Paint-by-Example"

**Comment by hywang2002** [comment]
hi, thank you for your intersest. you can download models from huggingface (https://huggingface.co/Fantasy-Studio/Paint-by-Example), and modify the corresponding path.
