### ISSUE TITLE
A few questions about warping

### ISSUE THREAD

**Issue by qiqigit** [hywang2002/MV-VTON#15]
Thank you for sharing this great work!
I have a few questions regarding the paper:
1. In Appendix A of the paper, you mentioned that you adopt "PF-AFN and GP-VTON to obtain the pre-warped cloth on frontal-view try-on task." 
>>Did you warp the cloth with both PF-AFN and GP-VTON and chose the better one of the 2 results as the pre-warped cloth?

2. Still in Appendix A, you wrote "... following previous works, we adopt PF-AFN and GP-VTON...; and we utilize StableVITON to get it on multi-view try-on task." 
>>Could you clarify the sentence a little bit more? What exactly did you do with StableVITON?
 

             Hi, thank you for your interest in our work. Following previous work (DCI-VTON), we use a pre-warped cloth to enhance the performance. We will implement this for more general purpose after accept.

_Originally posted by @hywang2002 in https://github.com/hywang2002/MV-VTON/issues/14#issuecomment-2437672120_

**Comment by hywang2002** [comment]
Hi, thank you for your interest in our work.

for 1, we use PF-AFN for VITON-HD dataset and GP-VTON for DressCode dataset, since PF-AFN don't release ckpts on DressCode dataset.

for 2, we use the parsing image to modify the output structure of StableVITON so that it outputs pre-warped cloth.
