### ISSUE TITLE
Suggestions for Improving Folder Structure and Code Organization

### ISSUE THREAD

**Issue by ShenZheng2000** [hywang2002/MV-VTON#16]
Thank you for your great work!! I have two suggestions to improve the project

**Folder Name**: Replace `Frontal-View VTON` with `Frontal-View-VTON` to avoid issues with spaces.

**Code Duplication**:
* `configs/viton512.yaml` and `Frontal-View VTON/configs/viton512.yaml` differ only in `dataroot`. I suggest using one as a base config and inherit the other.

* `main.py` and `Frontal-View VTON/main.py` differ mainly in `model.requires_grad_(False)`. Refactoring to inherit or extend would reduce redundancy.

**Comment by Ruanyx1823** [comment]
Dear Sir or Madam:
Hi, I am a sophomore computer science student. I've encountered some problems while reproducing the code of this MV-VTON article, and I wonder if you can help me out.
1.There are two files inside the MVG dataset, one is MVG and the other is MVG-pre-warped, and I would like to ask if both of them should be used right? What directory are these two to be put in, or are they on the same level as MV-VTON?
2. The VITON-HD link has the dataset and the pre-warped model. Do I have to download both? And then what directory do they go into?
3. If it's easier, can you give me a picture of what's in each file?
I would appreciate it if you could get back to me as soon as possible.

**Comment by git-hub-ai007** [comment]
Hi, I encountered the same issue.

**Comment by hywang2002** [comment]
> Thank you for your great work!! I have two suggestions to improve the project
> 
> **Folder Name**: Replace `Frontal-View VTON` with `Frontal-View-VTON` to avoid issues with spaces.
> 
> **Code Duplication**:
> 
> * `configs/viton512.yaml` and `Frontal-View VTON/configs/viton512.yaml` differ only in `dataroot`. I suggest using one as a base config and inherit the other.
> * `main.py` and `Frontal-View VTON/main.py` differ mainly in `model.requires_grad_(False)`. Refactoring to inherit or extend would reduce redundancy.

Hi, thank you very much for your interest and suggestions! We will consider making further improvements.

**Comment by hywang2002** [comment]
> Dear Sir or Madam: Hi, I am a sophomore computer science student. I've encountered some problems while reproducing the code of this MV-VTON article, and I wonder if you can help me out. 1.There are two files inside the MVG dataset, one is MVG and the other is MVG-pre-warped, and I would like to ask if both of them should be used right? What directory are these two to be put in, or are they on the same level as MV-VTON? 2. The VITON-HD link has the dataset and the pre-warped model. Do I have to download both? And then what directory do they go into? 3. If it's easier, can you give me a picture of what's in each file? I would appreciate it if you could get back to me as soon as possible.

Hi, thank you for your interest.

1. We follow the previous DCI-VTON to use pre-warped cloth, and train and reason on the pre-warped person image

2. ckpt and dataset can be placed where you want, as long as they correspond to the following two parts, or follow the path in the github code.
![image](https://github.com/user-attachments/assets/8a0c16e9-30f4-4705-82a2-09f370abba2f)

3. The structure of the project is the same as in this repo
