### ISSUE TITLE
Imports in the codebase point to local files

### ISSUE THREAD

**Issue by ouhenio** [hywang2002/MV-VTON#17]
Some imports in the code base, like the `CLIPVisionModel` [here](https://github.com/hywang2002/MV-VTON/blob/a29fd5fdfeca3b47f8db091630bf3fd36d92877f/ldm/modules/encoders/modules.py#L146) and `UNet2DConditionModel` [here](https://github.com/hywang2002/MV-VTON/blob/a29fd5fdfeca3b47f8db091630bf3fd36d92877f/ldm/models/diffusion/ddpm.py#L572) point to local files.

I don't know if the code is suposed to use finetuned versions of these models, but changing the paths to the corresponding standard huggingface versions seem to at least make the code work.

**Comment by hywang2002** [comment]
Hi, thank you for your interest in this work.

we use the pre-download ckpts from huggingface. you can replace these path with
1. https://huggingface.co/openai/clip-vit-large-patch14
2. https://huggingface.co/Fantasy-Studio/Paint-by-Example

I apologize for the confusion this has caused you.
