### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by gabrieletiboni** [hywang2002/MV-VTON#18]
Great work! I just have one question as I went through you paper: what is the inference time of the model for one test sample, roughly speaking? Including considerations such as preprocessing (pre-warped images) and what not.

Thank you in advance!

**Comment by hywang2002** [comment]
Hi, thank you for your attention.

Considering the time overhead of the pre-warp step, the inference time for frontal-view tasks is about 4s, and 8s for multi-view tasks. These are just rough estimates.

**Comment by KeesariVigneshwarReddy** [comment]
For the inference time for frontal-view tasks is about 4s, and 8s for multi-view tasks.

What is the hardware specification?
